### ISSUE TITLE
"pep8 ." is unhappy with PyTAP

### ISSUE THREAD

**Issue by shlomif** [rjbs/PyTAP#8]
Hi,

running "pep8 ." on the PyTAP git master sources emits some output (see https://pypi.python.org/pypi/pep8 ):

```text
shlomif@telaviv1:~/Download/unpack/prog/pytap$ pep8 . | head
./setup.py:5:7: E221 multiple spaces before operator
./setup.py:5:7: E251 unexpected spaces around keyword / parameter equals
./setup.py:5:12: E251 unexpected spaces around keyword / parameter equals
./setup.py:6:10: E251 unexpected spaces around keyword / parameter equals
./setup.py:6:12: E251 unexpected spaces around keyword / parameter equals
./setup.py:7:13: E251 unexpected spaces around keyword / parameter equals
./setup.py:7:15: E251 unexpected spaces around keyword / parameter equals
./setup.py:7:17: E201 whitespace after '['
./setup.py:7:30: E202 whitespace before ']'
./TAP/Simple.py:7:1: E302 expected 2 blank lines, found 1
shlomif@telaviv1:~/Download/unpack/prog/pytap$ 

```

I was notified of that after being recommended to use the "pep8" utility by the Debian mentors for Freeecell Solver, which includes a copy of pyTAP.

Do you think the code should be pep8-clean (with tests for that)?

**Comment by rjbs** [comment]
This strikes me as absurd.  90% of these changes are to `setup.py`, which no one need ever see, and which will not become more readable with this change.  The single change to TAP.Simple is about consistency with some style that is not the style I work in.

I am only slightly opposed to "You should format your code the same way as everyone else," but when it gets down to things like "put two blank lines here" and "don't put a space around a single string inside a list," I think it's gotten a bit ridiculous.

**Comment by rjbs** [comment]
I'm closing this until/unless someone can explain a concrete reason to change.
